### ISSUE TITLE
Some gedit-plugins fail to run due to python dependencies

### ISSUE THREAD

**Issue by LeonardKoenig** [flathub/org.gnome.gedit#25]
Hello,

enabling the some plugins with Preferences -> Plugins -> [SyncTeX/Character Map/Terminal/Git] fails with:

# SyncTeX

```
** (gedit:2): WARNING **: 17:21:07.440: Error importing plugin 'synctex':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/lib/gedit/plugins/synctex/__init__.py", line 7, in <module>
    from .synctex import SynctexAppActivatable, SynctexWindowActivatable
  File "/app/lib/gedit/plugins/synctex/synctex.py", line 24, in <module>
    from .evince_dbus import EvinceWindowProxy
  File "/app/lib/gedit/plugins/synctex/evince_dbus.py", line 22, in <module>
    import dbus, subprocess
ModuleNotFoundError: No module named 'dbus'

(gedit:2): libpeas-WARNING **: 17:21:07.440: Error loading plugin 'synctex'
```

# Character Map
```

** (gedit:2): WARNING **: 17:34:03.411: Error importing plugin 'charmap':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/lib/gedit/plugins/charmap/__init__.py", line 26, in <module>
    gi.require_version('Gucharmap', '2.90')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gucharmap not available

(gedit:2): libpeas-WARNING **: 17:34:03.412: Error loading plugin 'charmap'
```

# Embedded Terminal
```
** (gedit:2): WARNING **: 17:35:04.315: Error importing plugin 'terminal':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/lib/gedit/plugins/terminal.py", line 28, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available

(gedit:2): libpeas-WARNING **: 17:35:04.315: Error loading plugin 'terminal'
```

# Git
```

** (gedit:2): WARNING **: 17:35:37.871: Error importing plugin 'git':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/lib/gedit/plugins/git/__init__.py", line 23, in <module>
    gi.require_version('Ggit', '1.0')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Ggit not available

(gedit:2): libpeas-WARNING **: 17:35:37.871: Error loading plugin 'git'
```

# Missing dependencies

As far as I can tell the python-module `dbus` as well as the libraries for gucharmap, vte3 and libgit2-glib are missing (taken from the Arch Linux package names).

While the other plugins load fine, it's unclear whether they load missing packages on runtime or silently fail. Also I'm not sure whether the above dependencies are sufficient to get the mentioned plugins working. I additionally ran:

```
$ flatpak run --command=sh org.gnome.gedit
[ org.gnome.gedit ~]$ find /app/lib/gedit/plugins/ -name "*.py" -exec grep 'import ' {} +
```

Which yields some packages other than GTK/GDK related things being imported, such as `shutil`, `xml`, `codecs`, `weakref`, or `json`, `tempfile`.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I am believing that the most good resolution of this problem is separation of the plugins as flatpaks, of which the plugins that are requiring Python install Python as a flatpak as an extension for themselves. This shall minimise unnecessary dependencies, maximise shared usage of necessary dependencies, and ensure more security.

Is what I have stated possible? If not, I shall open an issue at http://github.com/flatpak/flatpak for it.

**Comment by TingPing** [comment]
It is possible to make an extension point, but it would require a bit of work and a small patch to gedit to load extensions from a different path probably.

**Comment by TingPing** [comment]
However I think most of these were fixed by https://github.com/flathub/org.gnome.gedit/commit/74772de30618bf71e86e8c4622238a0144b74b69

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
> http://github.com/flathub/org.gnome.gedit/issues/25#issuecomment-918196954

Indeed, they probably were remediated, but I am believing that the only ideal method of handling these extensions would be conversion of them to Flatpaks, and subsequent usage of them for this, because it would allow other software that uses them (like Python) to serve identical dependencies, without unnecessary duplication. If I create an issue for this, shall you leave it open for me whilst I ascertain how to perform this compartmentalization?
