### ISSUE TITLE
Embedded Terminal plugin is missing vte

### ISSUE THREAD

**Issue by julianfairfax** [flathub/org.gnome.gedit#56]
When I enable the plugin, it doesn't work. This is what the log of running gedit in the terminal shows:
```
** (gedit:2): WARNING **: 07:29:43.935: Error importing plugin 'terminal':
Traceback (most recent call last):
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/lib/gedit/plugins/terminal.py", line 28, in <module>
    gi.require_version('Vte', '2.91')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Vte not available

(gedit:2): libpeas-WARNING **: 07:29:43.935: Error loading plugin 'terminal'
```

**Comment by julianfairfax** [comment]
> Should be easy to build, maybe VTE used to be in the runtime.

Is there anything I can do to fix it or do I just wait for a fix to be released?

**Comment by TingPing** [comment]
Sure you can help. Revert this commit https://github.com/flathub/org.gnome.gedit/commit/2c5ea9a7b6d3d00ca40fc01c9e7cfc770a9e1016 and maybe update the version.
